#! /bin/bash
FONT="JetBrains Mono:size=10"
COLOR_BG="#1e1e1e"
COLOR_FG="#e4e4e4"

PANEL_FIFO=/tmp/panel_fifo

if [ $(pgrep panel_bar -c) -gt 0 ]; then
	pkill panel_bar
fi

if [ $(pgrep loop_mod -c) -gt 0 ]; then
	pkill loop_mod
fi


[ -f "$PANEL_FIFO" ] && rm ".PANEL_FIFO"
mkfifo $PANEL_FIFO

#Modules
bspc subscribe report > $PANEL_FIFO &
~/.config/panel/panel_loop> $PANEL_FIFO &

# Run the bar
~/.config/panel/panel_bar < $PANEL_FIFO | lemonbar -f "$FONT" -B $COLOR_BG -F $COLOR_FG

exit 0
