#! /bin/bash
FONT="JetBrains Mono:size=10"
COLOR_BG="#1e1e1e"
COLOR_FG="#e4e4e4"

if [ $(pgrep panel_bar -c) -gt 0 ]; then
	pkill panel_bar
fi
if [ $(pgrep loop_mod -c) -gt 0 ]; then
	pkill loop_mod
fi


[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo PANEL_FIFO

#TODO Remove relative filepath
#TODO Modularize all components
bspc subscribe report > PANEL_FIFO &
~/.config/panel/loop_mod > PANEL_FIFO &

~/.config/panel/panel_bar < PANEL_FIFO | lemonbar -f "$FONT" -B $COLOR_BG -F $COLOR_FG

exit 0
