#! /bin/bash

# modules
Clock() 
{
        DATETIME=$(date "+%a %b %d, %H:%M")
        echo -n "$DATETIME"
}

Battery() 
{
		local CAPACITY=$(cat /sys/class/power_supply/BAT0/capacity)
		local STATUS=$(cat /sys/class/power_supply/BAT0/status)
		[[ "$STATUS" == "Discharging" ]] &&  echo -n "$CAPACITY%" || echo -n "$STATUS, $CAPACITY%" 
}

network() 
{
	IPADDR=$(ip -brief address | grep UP )
	IP=$(echo "$IPADDR" | grep -Eo "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}")
	INTERFACE=$( echo "$IPADDR" | awk '{print $1}' )
	[[ "$INTERFACE" == "" ]] && echo "dowm" || echo "$INTERFACE: $IP"
}

volume()
{
	ISMUTED=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
	VOL=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -Eo "[0-9]{1,3}\%" | head -n 1)
    [[ "$ISMUTED" == "no" ]] && echo "vol: $VOL" || echo "muted"
}

desktops () 
{
	DESKTOPS=$(bspc query -D --names)
	FOCUSED=$(bspc query -D -d focused --names)

	echo "$DESKTOPS" | while read line; do
		echo "$FOCUSED" | while read foc; do
			[[ "$line" == "$foc" ]] && echo -n  " %{F#e4e4e4}$foc%{F-}" || echo -n " %{F#3A3A3A}$line%{F-}" 
		done
	done
}

# Event Loop
while true; do
	echo "%{l} $(desktops) %{c}$(Clock)%{r} $(volume) | $(network) | $(Battery) " 
        sleep 0.5
done
