#! /bin/bash

#Modules to update at a fixed time interval (1 sec)
#TODO: unscuff volume

Clock() 
{
        DATETIME=$(date "+%a %b %d, %H:%M")
        echo -n "$DATETIME"
}

Battery() 
{
		if [ -f /sys/class/power_supply/BAT0/capacity ]; then
			local CAPACITY=$(cat /sys/class/power_supply/BAT0/capacity)
			local STATUS=$(cat /sys/class/power_supply/BAT0/status)
			[[ "$STATUS" == "Discharging" ]] &&  echo -n "$CAPACITY%" || echo -n "$STATUS, $CAPACITY%" 
		fi
}

network() 
{
	IPADDR=$(ip -brief address | grep UP )
	IP=$(echo "$IPADDR" | grep -Eo "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}")
	INTERFACE=$( echo "$IPADDR" | awk '{print $1}' )
	[[ "$INTERFACE" == "" ]] && echo "down" || echo "$INTERFACE: $IP"
}

Volume()
{
	ISMUTED=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
	VOL=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -Eo "[0-9]{1,3}\%" | head -n 1)
    [[ "$ISMUTED" == "no" ]] && echo "vol: $VOL" || echo "muted"
}

# Capitol letter is to map the output
while true; do
	echo "C$(Clock)" || exit 1
	echo "N$(network)"
	echo "B$(Battery)" 
	echo "V$(Volume)"
	sleep 1
done
