#! /bin/bash

# Reads from fifo and writes to lemonbar

COLOR_FREE="#3A3A3A"
COLOR_OCCUPIED="#e4e4e4"
COLOR_FOCUSED="#9CDCFE"
COLOR_URGENT="#cd3131"

while read -r input ; do
	case $input in
		C*)
			CLOCK=${input:1}
			;;
		N*)
			NETWORK=${input:1}
			;;
		B*)
			BATTERY=${input:1}
			;;
		V*)
			VOLUME=${input:1}
			;;
		W*)
			DESKTOPS=""
			IFS=':'
			read -r -a array <<< "$input"
			for elem in "${array[@]}"
			do
				# DESKTOPS+="${elem:1} "
				case $elem in
					f*)
						#free desktop
						DESKTOPS+="%{F$COLOR_FREE}${elem:1}%{F-} "
						;;
					F*) 
						#focused free desktop
						DESKTOPS+="%{F$COLOR_FOCUSED}${elem:1}%{F-} "
						;;
					o*)
						#occupied desktop
						DESKTOPS+="%{F$COLOR_OCCUPIED}${elem:1}%{F-} "
						;;
					O*)
						#focused occupied desktop
						DESKTOPS+="%{F$COLOR_FOCUSED}${elem:1}%{F-} "
						;;
					u*)
						#urgent desktop
						DESKTOPS+="%{F$COLOR_URGENT}${elem:1}%{F-} "
						;;
					U*)
						#urgent focused desktop
						DESKTOPS+="%{F$COLOR_FOCUSED}${elem:1}%{F-} "
						;;
				esac
			done
			;;
	esac
	#Format
	echo "%{Sl}%{l}  $DESKTOPS %{c}$CLOCK%{r} $VOLUME | $NETWORK $BATTERY " || exit 1
done

