---
- include_tasks: fedora.yml
  when: ansible_distribution == 'Fedora'

- name: Update dotfiles repository
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_local_location }}"
    update: yes
  ignore_errors: yes

- name: Create directory
  ansible.builtin.file:
    path: "$HOME/.config/alacritty"
    state: directory
    recurse: yes

- name: Create symbolic links for dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  loop: "{{ dotfiles_symlinks }}"
