[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[window]
decorations = "Buttonless"
startup_mode = "Maximized"

[window.padding]
x = 6
y = 6

[[hints.enabled]]
# command = "xdg-open" # On Linux/BSD
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[[hints.enabled]]
command = { program = "/Users/cararo/.dotfiles/.bin/open-in-code" }
mouse.enabled = true
binding = { key = "f", mods = "Control|Shift" }
regex = '(\.?([~\/])?[-a-zA-Z0-9_+-,.\/@()\[\]]+)(?:(?::|", line )(\d+))?'

[[hints.enabled]]
command = { program = "/Users/cararo/.dotfiles/.bin/send-to-vim" }
mouse.enabled = false
binding = { key = "v", mods = "Control|Shift" }
regex = '(\.?([~\/])?[-a-zA-Z0-9_+-,.\/@()\[\]]+)(?:(?::|", line )(\d+))?'
