version: "3"
services:
  syncthing:
    image: docker.io/syncthing/syncthing:latest
    container_name: ${HOSTNAME}.syncthing
    hostname: ${HOSTNAME}
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      # podman unshare chown 1000:1000 -R ~/.config/syncthing ~/sync ~/books
      - /home/${USER}/.config/syncthing:/var/syncthing/config:Z
      - /home/${USER}/books:/var/syncthing/books:Z
      - /home/${USER}/sync:/var/syncthing/Sync:Z
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
