#!/bin/sh

alias nv=nvim
alias py=python3

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

alias la='ls -a'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# fzf jump
alias cdf='cd $(find -type d | fzf --reverse)'

alias gl='git log --oneline --graph --abbrev-commit'

alias battery='cat /sys/class/power_supply/BAT0/capacity'

alias pm="pulsemixer"
