---
- name: Add terraform repository on dnf
  become: yes
  yum_repository:
    name: Terraform
    description: Hashicorp rpm registry
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    enabled: yes
    gpgcheck: yes
    state: present
