---
- include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include_tasks: fedora.yml
  when: ansible_distribution == 'Fedora'

- name: Install Terraform
  ansible.builtin.package:
    name: terraform
    state: present
