require("plugins")
require("keymaps")
require("settings")

require("telescope-config")
require("treesitter-config")
require("lsp-config")
require("autocompletion")
require("tree-config")
require("statusline")
