#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          8 

bspc config split_ratio          0.5
bspc config single_monocle 		 true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a \* state=tiled

bspc config focused_border_color "#e4e4e4"
# Start status bar
~/.config/panel/panel &

