#!/bin/bash

TARGETNAME=$1
USAGE="usage: initmd2pdf [NAME]"

[[ $# -ne 1 ]] && echo "$USAGE" 1>&2 && exit 1

if ! (command -v pandoc && command -v pdflatex ) &>/dev/null; then
  echo "Dependencies are missing!" 1>&2 && exit 1
fi

[[ -f "$TARGETNAME.md" ]] &&
  echo "File already exits!" 1>&2 && exit 1

echo "Creating template for $TARGETNAME..." 1>&2

touch "$TARGETNAME.md"
touch "$TARGETNAME.bib"
touch Makefile

# Dowload Resources
PANDOC_PATH="$HOME/.local/share/pandoc"

if ! [[ -f "$PANDOC_PATH/csl/ieee.csl" ]]; then
  mkdir -p "$PANDOC_PATH/csl"
  echo "Dowloading IEEE citation styles..." 1>&2
  wget -q --show-progress https://pandoc.org/demo/ieee.csl && \
    mv ieee.csl "$PANDOC_PATH/csl/."
fi

if ! [[ -f "$PANDOC_PATH/filters/diagram-generator.lua" ]]; then
  mkdir -p "$PANDOC_PATH/filters"
  echo "Downloading diagram generator filters..." 1>&2
  wget -q --show-progress \
    https://raw.githubusercontent.com/pandoc/lua-filters/master/diagram-generator/diagram-generator.lua && \
      mv diagram-generator.lua "$PANDOC_PATH/filters/."
fi

echo "TARGETNAME=$TARGETNAME" >Makefile

cat >> Makefile <<"END"

pdf: $(TARGETNAME).md
	pandoc $^ -f markdown -t pdf -o $(TARGETNAME).pdf \
		--citeproc \
		--csl=ieee.csl \
		--lua-filter=diagram-generator.lua

html: $(TARGETNAME).md
	pandoc $^ -o $(TARGETNAME).html \
		--mathml \
		--standalone \
		--self-contained \
		--citeproc \
		--csl=ieee.csl \
		--lua-filter=diagram-generator.lua

open: pdf
	(xdg-open $(TARGETNAME).pdf & disown) &> /dev/null
END

cat > "$TARGETNAME.md" <<END
---
title: $TARGETNAME
author: $USER
date: $(date +"%B %Y")
bibliography: $TARGETNAME.bib
---

# Heading

# Bibliography
END

cat >"$TARGETNAME.bib" <<"END"
@Book{title,
  author =   {Author},
  title =    {Title},
  publisher =    {Publisher},
  year =     2000
}
END

echo "Template created!" 1>&2
exit 0
