#!/usr/bin/env bash

if [ -z "$DOC_SEARCH_PATH" ]; then
  search_path="$HOME/books/"
else
  search_path="$DOC_SEARCH_PATH"
fi

total="$(find "$search_path" -maxdepth 5 | wc -l)"

if [[ $total -eq 0 ]]; then
  prompt="No files here!"
else
  prompt="File: "
fi

file_name="$(find "$search_path" -maxdepth 5 -type f | \
  awk -F'/' '{print $NF}' | \
  sort | \
  fzf-tmux -p --prompt "$prompt")"

if [[ -n $file_name ]]; then
  xdg-open "$(find "$search_path" -maxdepth 5 -name "$file_name" )" | disown &
fi

exit 0
