#!/usr/bin/env bash
INPUT=$1
PATH="/opt/homebrew/bin":$PATH # needed for alcritty launcher

TOP_LEVEL_DIR=$(git rev-parse --show-toplevel 2>/dev/null)
if [[ $TOP_LEVEL_DIR ]]; then
  if [[ $INPUT =~ ^[ab]/ ]]; then
    INPUT="${TOP_LEVEL_DIR}${INPUT:1}"
  fi
fi

SESSION=$(tmux display -p '#{session_name}' || tmux list-sessions | grep "(attached)" |  awk -F: '{print $1}')
WINDOW=$(tmux display -p '#{window_index}'|| tmux list-windows -t $SESSION | grep "(active)" |  awk -F: '{print $1}')
cd "$(tmux display -t "$SESSION:$WINDOW" -p -F "#{pane_current_path}")" || exit

FILE_AND_LINE=$(echo "$INPUT" | tr -d '()' | perl -nE 'use Cwd "realpath"; while (m/([~.\/]?[-a-zA-Z0-9_+.,\/@()\[\]]+)(?:(?::|", line )(\d+))?/g) { say (realpath($1). (defined($2) ? ":$2" : "")) if -e realpath($1) }')

[[ -z "$FILE_AND_LINE" ]] && exit
code --goto "$FILE_AND_LINE"
