#!/usr/bin/env bash
set -x

IFS=' ' read -r -a search_path <<< "$REPO_SEARCH_PATH"

prompt="Select project: "
repo_name="$( find "${search_path[@]}" -maxdepth 1 -not -path '*/[@.]*' -type d | \
  awk -F'/' '{print $NF}' | \
  sort | \
  uniq | \
  fzf-tmux -p --reverse --prompt "$prompt")"

if [[ -z $repo_name ]]; then 
  exit 0
fi

if [[ -n $repo_name ]]; then
  dir="$(find "${search_path[@]}" -maxdepth 1 -name "$repo_name")"
  tmux new-session -c "$dir" -s "$repo_name" -d
  tmux switch-client -t "$repo_name"
fi

exit 0
