#!/usr/bin/env bash

search_path="$DOC_SEARCH_PATH"
total="$(find "$search_path" -maxdepth 5 | wc -l)"

if [[ $total -eq 0 ]]; then
  prompt="No files here!"
else
  prompt="File: "
fi

file_name="$(find "$search_path" -maxdepth 5 -type f | \
  awk -F'/' '{print $NF}' | \
  sort | \
  fzf-tmux --reverse -p --prompt "$prompt")"

if [[ -n $file_name ]]; then
  xdg-open "$(find "$search_path" -maxdepth 5 -name "$file_name" )" | disown &
fi

exit 0
