#!/usr/bin/env bash
# Open in file in vim. Requires tmux.
#
INPUT=$1
PATH="/opt/homebrew/bin":$PATH # needed for alcritty launcher

SESSION=$(tmux display -p '#{session_name}' || tmux list-sessions | grep "(attached)" |  awk -F: '{print $1}')
WINDOW=$(tmux display -p '#{window_index}'|| tmux list-windows -t $SESSION | grep "(active)" |  awk -F: '{print $1}')
VIM_PANE_ID=$(tmux list-panes -t "$SESSION:$WINDOW" -F '#{pane_id} #{pane_current_command}' | grep -i vim | awk '{print $1}')
cd "$(tmux display -t "$SESSION:$WINDOW" -p -F "#{pane_current_path}")" || exit

FILE_PATH=$(realpath "$INPUT")
[[ -z "$FILE_PATH" ]] && exit

if [ -z "$VIM_PANE_ID" ]; then
    tmux send-keys -t "$SESSION:$WINDOW" "vim" C-m
    VIM_PANE_ID=$(tmux list-panes -t "$SESSION:$WINDOW" -F '#{pane_id} #{pane_current_command}' | grep -i vim | awk '{print $1}')
fi
tmux send-keys -t "$SESSION:$WINDOW.$VIM_PANE_ID" ":e $FILE_PATH" C-m
tmux select-pane -t "$VIM_PANE_ID"
