---
- hosts: all

  vars:
    dotfiles_repo: "https://github.com/Caw3/dotfiles.git"
    dotfiles_local_location: "~/.dotfiles"
    dotfiles_symlinks:
      - src: "{{ dotfiles_local_location }}/.bashrc"
        dest: "~/.bashrc"
      - src: "{{ dotfiles_local_location }}/.tmux.conf"
        dest: "~/.tmux.conf"
      - src: "{{ dotfiles_local_location }}/.vimrc"
        dest: "~/.vimrc"
      - src: "{{ dotfiles_local_location }}/.vim"
        dest: "~/.vim"
      - src: "{{ dotfiles_local_location }}/.gitconfig"
        dest: "~/.gitconfig"
      - src: "{{ dotfiles_local_location }}/.git_template"
        dest: "~/.git_template"

  tasks:
    - name: Install initial packages
      become: yes
      package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - openssh
        - wget
        - curl
        - tmux
        - vim
        - rsync

    - name: Update/Clone dotfiles repository
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_local_location }}"
        update: yes

    - name: Create symbolic links for dotfiles
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        force: yes
      loop: "{{ dotfiles_symlinks }}"
