---
- hosts: all
  become: yes
  tasks:

  - name: Install extra packages on Ubuntu
    apt:
      name: "{{ item }}"
      state: present
    loop:
    - docker
    - docker-compose
    - python3-pip
    - python3
    - shellcheck
    - gh
    - pandoc
    - awscli
    - htop
    - ddgr
    - autossh
    - fzf
    - nodejs
    - npm
    when: ansible_distribution == 'Ubuntu'

  - name: Add the user to the docker group
    ansible.builtin.user:
      name: ubuntu
      groups: docker
      append: yes
    when: ansible_distribution == 'Ubuntu'

  - name: Install extra packages on Fedora
    dnf:
      name: "{{ item }}"
      state: present
    loop:
    - podman
    - podman-compose
    - python3-pip
    - python3
    - ShellCheck
    - gh
    - pandoc
    - awscli
    - htop
    - ddgr
    - autossh
    - fzf
    - nodejs
    - npm
    when: ansible_distribution == 'Fedora'

  roles:
    - role: terraform
