---
- hosts: all
  become: yes

  tasks:
    - name: Install extra packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - podman
        - podman-compose
        - pip
        - shfmt
        - gh
        - pandoc
