---
- hosts: all
  become: yes
  tasks:

  - name: Install extra packages on Ubuntu
    apt:
      name: "{{ item }}"
      state: present
    loop:
    - docker
    - docker-compose
    - python3-pip
    - python3
    - shellcheck
    - gh
    - pandoc
    - awscli
    - htop
    - ddgr
    - autossh
    - fzf
    - nodejs
    - npm
    when: ansible_distribution == 'Ubuntu'

  - name: Add the user to the docker group
    ansible.builtin.user:
      name: ubuntu
      groups: docker
      append: yes
    when: ansible_distribution == 'Ubuntu'

  - name: Install extra packages on Fedora
    dnf:
      name: "{{ item }}"
      state: present
    loop:
    - podman
    - podman-compose
    - python3-pip
    - python3
    - ShellCheck
    - gh
    - pandoc
    - awscli
    - htop
    - ddgr
    - autossh
    - fzf
    - nodejs
    - npm
    when: ansible_distribution == 'Fedora'

  - name: Add terraform repository on dnf
    yum_repository:
      name: Terraform
      description: Infrastructure as code
      baseurl: https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
      enabled: yes
      gpgcheck: yes
      state: present
    when: ansible_distribution == 'Fedora'

  - name: Install required packages for terraform on apt
    apt:
      pkg:
        - software-properties-common
        - gnupg
        - wget
      state: present
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'

  - name: Add HashiCorp GPG key on apt
    apt_key:
      url: https://apt.releases.hashicorp.com/gpg
      state: present
    when: ansible_distribution == 'Ubuntu'

  - name: Get Ubuntu codename
    shell: lsb_release -cs
    register: ubuntu_codename
    when: ansible_distribution == 'Ubuntu'

  - name: Add HashiCorp repository
    apt_repository:
      repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ubuntu_codename.stdout }} main"
      state: present
      update_cache: yes

  - name: Install Terraform
    ansible.builtin.package:
      name: terraform
      state: present
